---
- name: Deference the instance facts
  set_fact:
    instance_facts_item: "{{ instance_facts_dict[cloud_instance_item.name] }}"

- name: Create interfaces list
  set_fact:
    instance_interfaces: []

- include_tasks: "aws-interface.yml"
  with_indexed_items: "{{ cloud_instance_item.interfaces | default([]) }}"
  loop_control:
    loop_var: cloud_interface_item

- name: Set the IP address for the instance
  set_fact:
    instance_ip_address: "{{ instance_facts_item.public_ip_address | default(instance_facts_item.private_ip_address, true) }}"

- name: Add host to inventory
  add_host:
    hostname: "{{ instance_facts_item.tags.Name }}"
    ansible_host: "{{ instance_ip_address }}"
    ansible_user: "{{ cloud_instance_item.cloud_user | default(cloud_user) }}"
    groups: "{{ instance_facts_item.tags.groups | default(omit) }}"
    ansible_network_os: "{{ instance_facts_item.tags.network_os | default(omit) }}"
    private_ip_address: "{{ instance_facts_item.private_ip_address }}"
    interfaces: "{{ instance_interfaces }}"
    cloud_template_item: "{{ cloud_instance_item }}"
    cloud_vpc_data: "{{ cloud_vpc_data }}"
